name: Docker Workflow

on:
  push:

env: #remove this ðŸ‘ˆ
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: health-app
  DOCKER_USERNAME: markfosu
# DOCKER_PASSWORD: PrintTest!243! 
  DOCKER_HUB_TOKEN: dckr_pat_gUys1Z4LCrmMBQcmJVvT5Lecx0k

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
      # run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        run: echo "$DOCKER_HUB_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Docker Publish
        run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
      # run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
        run: echo "$DOCKER_HUB_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Docker Run
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest